services:
  # gem-server:
  #   env_file:
  #      - .env
  #   # todo

  mongodb:
    image: mongo:7.0.12
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ADMIN}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - ${MONGO_STORAGE_PATH}:/data/db
    networks:
      - gems-network

networks:
  gems-network:
    driver: bridge